//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnderstoodDotOrg.Domain {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Import : global::System.Configuration.ApplicationSettingsBase {
        
        private static Import defaultInstance = ((Import)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Import())));
        
        public static Import Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("master")]
        public string MasterDatabaseName {
            get {
                return ((string)(this["MasterDatabaseName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("web")]
        public string WebDatabaseName {
            get {
                return ((string)(this["WebDatabaseName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{C9DFC576-7750-4A84-9A79-61F16585E64E}")]
        public string ReviewTemplateGUID {
            get {
                return ((string)(this["ReviewTemplateGUID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{B793F0F5-2857-4379-99B9-EC1D132C887F}")]
        public string MetadataTemplateGUID {
            get {
                return ((string)(this["MetadataTemplateGUID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{03877E4C-8EDD-42CE-B94A-E27621C16745}")]
        public string ReviewsContainerGUID {
            get {
                return ((string)(this["ReviewsContainerGUID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/sitecore/media library/Images/Poses/Reviews/")]
        public string ImagesPath {
            get {
                return ((string)(this["ImagesPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{8DE67A64-0E64-47A5-87FD-5096F3979F55}")]
        public string CategoriesContainerGUID {
            get {
                return ((string)(this["CategoriesContainerGUID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{97908446-B312-4183-915E-2E43BA5A7693}")]
        public string GenreContainerGUID {
            get {
                return ((string)(this["GenreContainerGUID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{042EBC5C-CCA0-4758-823D-A07213A72434}")]
        public string PlatformContainerGUID {
            get {
                return ((string)(this["PlatformContainerGUID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0AC054FE-599B-4B8A-B5A2-BA805260674B}")]
        public string SkillsContainerGUID {
            get {
                return ((string)(this["SkillsContainerGUID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{11AAE042-9BFA-43C4-A971-0AF140108921}")]
        public string SubjectsContainerGUID {
            get {
                return ((string)(this["SubjectsContainerGUID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{88226E2B-BAFE-44E9-8EEE-95525458EA14}")]
        public string TypesContainerGUID {
            get {
                return ((string)(this["TypesContainerGUID"]));
            }
        }
    }
}
