using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Text;
using System.Threading.Tasks;


namespace UnderstoodDotOrg.Domain.Membership
{
    /// <summary>
    /// Provides a wrapper for Entity DbContext that allows custom connection string. Default code generated by Entity does not support custom connection strings
    /// </summary>
    public partial class Membership : DbContext
    {
        /// <summary>
        /// Creates a new instance of Entity DbContext for Membership using the provided connection string
        /// </summary>
        /// <param name="connectionString">Valid Entity connection string to use for this instance</param>
        public Membership(string connectionString)
            : base(connectionString)
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    }
}
