//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnderstoodDotOrg.Web.Presentation.Sublayouts.Account {
    
    
    public partial class AccountProfile {
        
        /// <summary>
        /// ucAccountHeader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UnderstoodDotOrg.Web.Presentation.Sublayouts.Account.AccountHeader ucAccountHeader;
        
        /// <summary>
        /// ucAccountNonFriendProfile control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UnderstoodDotOrg.Web.Presentation.Sublayouts.Account.AccountNonFriendProfile ucAccountNonFriendProfile;
        
        /// <summary>
        /// pnlFriends control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlFriends;
        
        /// <summary>
        /// litCommentCount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litCommentCount;
        
        /// <summary>
        /// ddlMobileTabs control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlMobileTabs;
        
        /// <summary>
        /// ucAccountFriendProfile control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UnderstoodDotOrg.Web.Presentation.Sublayouts.Account.AccountFriendProfile ucAccountFriendProfile;
        
        /// <summary>
        /// ucAccountFriendConnections control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UnderstoodDotOrg.Web.Presentation.Sublayouts.Account.AccountFriendConnections ucAccountFriendConnections;
        
        /// <summary>
        /// ucAccountFriendComments control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UnderstoodDotOrg.Web.Presentation.Sublayouts.Account.AccountFriendComments ucAccountFriendComments;
    }
}
